# Generated by Django 4.1.4 on 2022-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposComputo',
            fields=[
                ('codigo_activo_fijo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
